<?xml version="1.0" encoding="utf-8"?>
<Database Name="DB_PhieuDuyetGia" Class="DBContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=KHANG-KT\SQLEXPRESS;Initial Catalog=DB_PhieuDuyetGia;Integrated Security=True" SettingsObjectName="PRJ_PhieuDuyetGia_VLA.My.MySettings" SettingsPropertyName="DB_PhieuDuyetGiaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SX_PhieuDuyetGia" Member="SX_PhieuDuyetGias">
    <Type Name="SX_PhieuDuyetGia">
      <Column Name="ID" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SoPhieu" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="TenPhieu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DonViSuDung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EditedOn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EditedBy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TrangThaiDuyet" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SX_PhieuDuyetGia_ChiTiet" Member="SX_PhieuDuyetGia_ChiTiets">
    <Type Name="SX_PhieuDuyetGia_ChiTiet">
      <Column Name="ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDPhieuDuyetGia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DonViSuDung" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EditedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EditedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoDonHang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenDonVi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TenSanPham" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuyCachSanPham" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="GiayRuot" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="GiayBia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LaiDinhMuc" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DonGiaTinh" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
</Database>