'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.9151
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<System.Data.Linq.Mapping.DatabaseAttribute(Name:="DB_PhieuDuyetGia")>  _
Partial Public Class DBContextDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.PRJ_PhieuDuyetGia_VLA.My.MySettings.Default.DB_PhieuDuyetGiaConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property SX_PhieuDuyetGias() As System.Data.Linq.Table(Of SX_PhieuDuyetGia)
		Get
			Return Me.GetTable(Of SX_PhieuDuyetGia)
		End Get
	End Property
	
	Public ReadOnly Property SX_PhieuDuyetGia_ChiTiets() As System.Data.Linq.Table(Of SX_PhieuDuyetGia_ChiTiet)
		Get
			Return Me.GetTable(Of SX_PhieuDuyetGia_ChiTiet)
		End Get
	End Property
End Class

<Table(Name:="dbo.SX_PhieuDuyetGia")>  _
Partial Public Class SX_PhieuDuyetGia
	
	Private _ID As String
	
	Private _SoPhieu As String
	
	Private _TenPhieu As String
	
	Private _TrangThai As System.Nullable(Of Boolean)
	
	Private _DonViSuDung As System.Nullable(Of Integer)
	
	Private _CreatedBy As System.Nullable(Of Integer)
	
	Private _CreatedOn As System.Nullable(Of Date)
	
	Private _EditedOn As System.Nullable(Of Integer)
	
	Private _EditedBy As System.Nullable(Of Date)
	
	Private _GhiChu As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Column(Storage:="_ID", DbType:="NVarChar(100)")>  _
	Public Property ID() As String
		Get
			Return Me._ID
		End Get
		Set
			If (String.Equals(Me._ID, value) = false) Then
				Me._ID = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_SoPhieu", DbType:="NVarChar(25)")>  _
	Public Property SoPhieu() As String
		Get
			Return Me._SoPhieu
		End Get
		Set
			If (String.Equals(Me._SoPhieu, value) = false) Then
				Me._SoPhieu = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_TenPhieu", DbType:="NVarChar(250)")>  _
	Public Property TenPhieu() As String
		Get
			Return Me._TenPhieu
		End Get
		Set
			If (String.Equals(Me._TenPhieu, value) = false) Then
				Me._TenPhieu = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_TrangThai", DbType:="Bit")>  _
	Public Property TrangThai() As System.Nullable(Of Boolean)
		Get
			Return Me._TrangThai
		End Get
		Set
			If (Me._TrangThai.Equals(value) = false) Then
				Me._TrangThai = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_DonViSuDung", DbType:="Int")>  _
	Public Property DonViSuDung() As System.Nullable(Of Integer)
		Get
			Return Me._DonViSuDung
		End Get
		Set
			If (Me._DonViSuDung.Equals(value) = false) Then
				Me._DonViSuDung = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_CreatedBy", DbType:="Int")>  _
	Public Property CreatedBy() As System.Nullable(Of Integer)
		Get
			Return Me._CreatedBy
		End Get
		Set
			If (Me._CreatedBy.Equals(value) = false) Then
				Me._CreatedBy = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_CreatedOn", DbType:="DateTime")>  _
	Public Property CreatedOn() As System.Nullable(Of Date)
		Get
			Return Me._CreatedOn
		End Get
		Set
			If (Me._CreatedOn.Equals(value) = false) Then
				Me._CreatedOn = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_EditedOn", DbType:="Int")>  _
	Public Property EditedOn() As System.Nullable(Of Integer)
		Get
			Return Me._EditedOn
		End Get
		Set
			If (Me._EditedOn.Equals(value) = false) Then
				Me._EditedOn = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_EditedBy", DbType:="DateTime")>  _
	Public Property EditedBy() As System.Nullable(Of Date)
		Get
			Return Me._EditedBy
		End Get
		Set
			If (Me._EditedBy.Equals(value) = false) Then
				Me._EditedBy = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_GhiChu", DbType:="NVarChar(500)")>  _
	Public Property GhiChu() As String
		Get
			Return Me._GhiChu
		End Get
		Set
			If (String.Equals(Me._GhiChu, value) = false) Then
				Me._GhiChu = value
			End If
		End Set
	End Property
End Class

<Table(Name:="dbo.SX_PhieuDuyetGia_ChiTiet")>  _
Partial Public Class SX_PhieuDuyetGia_ChiTiet
	
	Private _ID As String
	
	Private _IDPhieuDuyetGia As String
	
	Private _DonViSuDung As String
	
	Private _TrangThai As System.Nullable(Of Boolean)
	
	Private _CreatedOn As String
	
	Private _CreatedBy As String
	
	Private _EditedOn As String
	
	Private _EditedBy As String
	
	Private _SoDonHang As String
	
	Private _TenDonVi As String
	
	Private _TenSanPham As String
	
	Private _SoLuong As String
	
	Private _QuyCachSanPham As String
	
	Private _GiayRuot As String
	
	Private _GiayBia As String
	
	Private _LaiDinhMuc As String
	
	Private _DonGiaTinh As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Column(Storage:="_ID", DbType:="NChar(10)")>  _
	Public Property ID() As String
		Get
			Return Me._ID
		End Get
		Set
			If (String.Equals(Me._ID, value) = false) Then
				Me._ID = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_IDPhieuDuyetGia", DbType:="NChar(10)")>  _
	Public Property IDPhieuDuyetGia() As String
		Get
			Return Me._IDPhieuDuyetGia
		End Get
		Set
			If (String.Equals(Me._IDPhieuDuyetGia, value) = false) Then
				Me._IDPhieuDuyetGia = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_DonViSuDung", DbType:="NChar(10)")>  _
	Public Property DonViSuDung() As String
		Get
			Return Me._DonViSuDung
		End Get
		Set
			If (String.Equals(Me._DonViSuDung, value) = false) Then
				Me._DonViSuDung = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_TrangThai", DbType:="Bit")>  _
	Public Property TrangThai() As System.Nullable(Of Boolean)
		Get
			Return Me._TrangThai
		End Get
		Set
			If (Me._TrangThai.Equals(value) = false) Then
				Me._TrangThai = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_CreatedOn", DbType:="NChar(10)")>  _
	Public Property CreatedOn() As String
		Get
			Return Me._CreatedOn
		End Get
		Set
			If (String.Equals(Me._CreatedOn, value) = false) Then
				Me._CreatedOn = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_CreatedBy", DbType:="NChar(10)")>  _
	Public Property CreatedBy() As String
		Get
			Return Me._CreatedBy
		End Get
		Set
			If (String.Equals(Me._CreatedBy, value) = false) Then
				Me._CreatedBy = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_EditedOn", DbType:="NChar(10)")>  _
	Public Property EditedOn() As String
		Get
			Return Me._EditedOn
		End Get
		Set
			If (String.Equals(Me._EditedOn, value) = false) Then
				Me._EditedOn = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_EditedBy", DbType:="NChar(10)")>  _
	Public Property EditedBy() As String
		Get
			Return Me._EditedBy
		End Get
		Set
			If (String.Equals(Me._EditedBy, value) = false) Then
				Me._EditedBy = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_SoDonHang", DbType:="NChar(10)")>  _
	Public Property SoDonHang() As String
		Get
			Return Me._SoDonHang
		End Get
		Set
			If (String.Equals(Me._SoDonHang, value) = false) Then
				Me._SoDonHang = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_TenDonVi", DbType:="NChar(10)")>  _
	Public Property TenDonVi() As String
		Get
			Return Me._TenDonVi
		End Get
		Set
			If (String.Equals(Me._TenDonVi, value) = false) Then
				Me._TenDonVi = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_TenSanPham", DbType:="NChar(10)")>  _
	Public Property TenSanPham() As String
		Get
			Return Me._TenSanPham
		End Get
		Set
			If (String.Equals(Me._TenSanPham, value) = false) Then
				Me._TenSanPham = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_SoLuong", DbType:="NChar(10)")>  _
	Public Property SoLuong() As String
		Get
			Return Me._SoLuong
		End Get
		Set
			If (String.Equals(Me._SoLuong, value) = false) Then
				Me._SoLuong = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_QuyCachSanPham", DbType:="NChar(10)")>  _
	Public Property QuyCachSanPham() As String
		Get
			Return Me._QuyCachSanPham
		End Get
		Set
			If (String.Equals(Me._QuyCachSanPham, value) = false) Then
				Me._QuyCachSanPham = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_GiayRuot", DbType:="NChar(10)")>  _
	Public Property GiayRuot() As String
		Get
			Return Me._GiayRuot
		End Get
		Set
			If (String.Equals(Me._GiayRuot, value) = false) Then
				Me._GiayRuot = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_GiayBia", DbType:="NChar(10)")>  _
	Public Property GiayBia() As String
		Get
			Return Me._GiayBia
		End Get
		Set
			If (String.Equals(Me._GiayBia, value) = false) Then
				Me._GiayBia = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_LaiDinhMuc", DbType:="NChar(10)")>  _
	Public Property LaiDinhMuc() As String
		Get
			Return Me._LaiDinhMuc
		End Get
		Set
			If (String.Equals(Me._LaiDinhMuc, value) = false) Then
				Me._LaiDinhMuc = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_DonGiaTinh", DbType:="NChar(10)")>  _
	Public Property DonGiaTinh() As String
		Get
			Return Me._DonGiaTinh
		End Get
		Set
			If (String.Equals(Me._DonGiaTinh, value) = false) Then
				Me._DonGiaTinh = value
			End If
		End Set
	End Property
End Class
